### ISSUE TITLE
Fix SSL Support in Python 3.8.x

### ISSUE THREAD

**Issue by infamousjoeg** [infamousjoeg/pyaim#26]
**Describe the bug**
When initializing `CCPPasswordREST` with `verify=True` the following error occurs:

```python
Traceback (most recent call last):
  File "/Users/joegarcia/Git/infamousjoeg/pyaim/pyaim/aimccp.py", line 83, in GetPassword
    conn.request("GET", url, headers=self._headers)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joegarcia/Git/infamousjoeg/pyaim/pyaim/aimccp.py", line 91, in GetPassword
    raise Exception(e)
Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
```

Validated that the SSL Certificates on https://cyberark.joegarcia.dev are valid and current.  They are supplied via LetsEncrypt.

**To Reproduce**
1. Init the `CCPPasswordREST` class with `verify=True` to verify all SSL certificates.
2. Either `check_service()` or `GetPassword` to receive the SSL error.

**Expected behavior**
No errors should occur and SSL should be verified successfully unless not from a Trusted Root.

**Comment by sgnn7** [comment]
@infamousjoeg Py3 API has a good workaround for that but it may be a bit tricky to read the code since that var gets passed around a lot

**Comment by infamousjoeg** [comment]
This has nothing to do with this library.

Navigate to
`cd /Applications/Python\ 3.8/`

Click on Install Certificates.command

This should solve it.

**Comment by jrbat76** [comment]
to: infamousjoeg
Thanks, I kept having the same issue with my both python3.8 and 3.9. Was not sure why. But you got it right. The error message did go away.
